name: eventuous
version: 0.0.9
homepage: https://eventuous.dev
description: A lightweight and open-souce Event Sourcing library for Dart.
repository: https://github.com/Eventuous/eventuous-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  uuid: ^3.0.4
  path: ^1.8.0
  meta: ^1.7.0
  logging: ^1.0.1
  equatable: ^2.0.0
  json_patch: ^3.0.0
  collection: ^1.15.0
  universal_io: ^2.0.4
  json_annotation: ^4.1.0
  eventstore_client: ^0.2.1
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.17.12
  build_runner: ^2.1.2
  docker_process: ^1.3.0
  json_serializable: ^5.0.0
