name: eventuous
version: 0.1.1
homepage: https://eventuous.dev
description: A lightweight and open-souce Event Sourcing library for Dart.
repository: https://github.com/Eventuous/eventuous-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  uuid: ^3.0.4
  path: ^1.8.0
  meta: ^1.7.0
  logging: ^1.0.1
  equatable: ^2.0.0
  json_patch: ^3.0.0
  collection: ^1.15.0
  universal_io: ^2.0.4
  json_annotation: ^4.6.0
  eventstore_client: ^0.6.1
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.2
  json_serializable: ^6.0.1
  eventstore_client_test: ^0.6.1
  eventuous_test: 
    path: ../eventuous_test
false_secrets:
  - test/certs/ca/ca.pem
  - test/certs/ca/ca.key
  - test/certs/node/node.key