name: eventuous
version: 0.0.1-prerelease
description: A lightweight and open-souce Event Sourcing library for Dart.
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  uuid: ^3.0.4
  meta: ^1.7.0
  logging: ^1.0.1
  eventstore_client: ^0.2.1
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.17.12
