name: eventuate
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  eventstore_client: ^0.2.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
