# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

analyzer:
  exclude:
    - lib/**.g.dart
    - test/**.g.dart
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    constant_identifier_names: ignore
