name: eventuous_test
version: 0.0.12
homepage: https://eventuous.dev
description: A library with utilities for testing eventuous
repository: https://github.com/Eventuous/eventuous-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  path: ^1.8.0
  logging: ^1.0.1
  eventuous: ^0.1.0
  equatable: ^2.0.0
  universal_io: ^2.0.4
  eventstore_client: ^0.2.1
  eventstore_client_test: ^0.2.1
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
