name: eventuous_annotation
version: 0.0.1-prerelease
homepage: https://eventuous.dev
description: Annotations for Eventuous code generation - a lightweight and open-souce Event Sourcing library for Dart.
repository: https://github.com/Eventuous/eventuous-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  eventuous: ^0.0.4

dependency_overrides:
  eventuous:
    path: ../eventuous

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
