name: example
description: An Eventuous generator example

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  eventuous: ^0.0.4
  json_annotation: ^4.1.0

dependency_overrides:
  eventuous:
    path: ../../eventuous

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  eventuous_generator:
    path: ../

