# Created with package:mono_repo v5.0.4
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.5
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.4
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKGS: packages/eventuous, packages/eventuous_generator, packages/eventuous_test; `dart analyze --fatal-infos .`, `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous-packages/eventuous_generator-packages/eventuous_test;commands:analyze-format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous-packages/eventuous_generator-packages/eventuous_test
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: packages_eventuous_pub_upgrade
        name: packages/eventuous; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventuous
        run: dart pub upgrade
      - name: "packages/eventuous; dart analyze --fatal-infos ."
        if: "always() && steps.packages_eventuous_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous
        run: dart analyze --fatal-infos .
      - name: "packages/eventuous; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_eventuous_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous
        run: "dart format --output=none --set-exit-if-changed ."
      - id: packages_eventuous_generator_pub_upgrade
        name: packages/eventuous_generator; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventuous_generator
        run: dart pub upgrade
      - name: "packages/eventuous_generator; dart analyze --fatal-infos ."
        if: "always() && steps.packages_eventuous_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous_generator
        run: dart analyze --fatal-infos .
      - name: "packages/eventuous_generator; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_eventuous_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous_generator
        run: "dart format --output=none --set-exit-if-changed ."
      - id: packages_eventuous_test_pub_upgrade
        name: packages/eventuous_test; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventuous_test
        run: dart pub upgrade
      - name: "packages/eventuous_test; dart analyze --fatal-infos ."
        if: "always() && steps.packages_eventuous_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous_test
        run: dart analyze --fatal-infos .
      - name: "packages/eventuous_test; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_eventuous_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous_test
        run: "dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
  job_003:
    name: "unit_test; PKG: packages/eventuous_generator; `dart test -j 1 --reporter=expanded`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous_generator;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous_generator
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: packages_eventuous_generator_pub_upgrade
        name: packages/eventuous_generator; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventuous_generator
        run: dart pub upgrade
      - name: "packages/eventuous_generator; dart test -j 1 --reporter=expanded"
        if: "always() && steps.packages_eventuous_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventuous_generator
        run: "dart test -j 1 --reporter=expanded"
    needs:
      - job_001
      - job_002
  job_004:
    name: "Test & Publish coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: "packages/eventuous; dart pub upgrade && pub global activate coverage"
        working-directory: packages/eventuous
        run: "dart pub upgrade && pub global activate coverage"
      - name: packages/eventuous; Run tests with coverage
        working-directory: packages/eventuous
        run: "dart test -j 1 --reporter=expanded --coverage=\"coverage\""
      - name: packages/eventuous; Collect test coverage
        working-directory: packages/eventuous
        run: "format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib"
      - name: Publish test coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - job_001
      - job_002
      - job_003
