# Created with package:mono_repo v5.0.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.2
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; `dart analyze --fatal-infos .`, `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:eventuous;commands:analyze-format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:eventuous
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: eventuous_pub_upgrade
        name: eventuous; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: eventuous
        run: dart pub upgrade
      - name: "eventuous; dart analyze --fatal-infos ."
        if: "always() && steps.eventuous_pub_upgrade.conclusion == 'success'"
        working-directory: eventuous
        run: dart analyze --fatal-infos .
      - name: "eventuous; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.eventuous_pub_upgrade.conclusion == 'success'"
        working-directory: eventuous
        run: "dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
  job_003:
    name: "unit_test; `dart test -j 1 --reporter=expanded --coverage=\"coverage\"`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:eventuous;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:eventuous
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: eventuous_pub_upgrade
        name: eventuous; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: eventuous
        run: dart pub upgrade
      - name: "eventuous; dart test -j 1 --reporter=expanded --coverage=\"coverage\""
        if: "always() && steps.eventuous_pub_upgrade.conclusion == 'success'"
        working-directory: eventuous
        run: "dart test -j 1 --reporter=expanded --coverage=\"coverage\""
    needs:
      - job_001
      - job_002
  job_004:
    name: Collect and publish coverage
    runs-on: ubuntu-latest
    steps:
      - name: Collect coverage
        run: "format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib"
      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - job_001
      - job_002
      - job_003
