name: eventuous_generator
version: 0.1.1
homepage: https://eventuous.dev
description: Code generator for Eventuous - a lightweight and open-souce Event Sourcing library for Dart.
repository: https://github.com/Eventuous/eventuous-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  analyzer: ^5.1.0
  build: ^2.1.0
  file: ^6.1.4
  grpc: ^3.0.2
  protobuf: ^2.1.0
  build_resolvers: ^2.0.0
  eventuous: ^0.1.1
  get_it: ^7.2.0
  glob: ^2.0.0
  path: ^1.8.0
  collection: ^1.15.0
  json_annotation: ^4.6.0
  source_gen: ^1.1.0
  shell: ^2.0.0
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
  build_test: ^2.1.3
  build_runner: ^2.0.1
  source_gen_test: ^1.0.0
  json_serializable: ^6.0.1
