name: eventuous_generator
version: 0.0.1-prerelease
homepage: https://eventuous.dev
description: Code generator for Eventuous - a lightweight and open-souce Event Sourcing library for Dart.
repository: https://github.com/Eventuous/eventuous-dart
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  analyzer: ^2.0.0
  build: ^2.1.0
  source_gen: ^1.1.0
  eventuous: ^0.0.4
dev_dependencies: 
  build_runner: ^2.0.0
  build_test: ^2.1.3
  pedantic: ^1.10.0
  source_gen_test: ^1.0.0
  test: ^1.16.0
dependency_overrides: 
  eventuous: 
    path: ../eventuous
